[package]
name = "voxalive-providers"
version = "0.1.0"
edition.workspace = true

[features]
raw = []
web3d = []

[dependencies]
voxalive-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tungstenite.workspace = true
url.workspace = true
tokio.workspace = true
whisper-rs = "0.11"
async-trait.workspace = true
